name: Docker Image CI

on: 
  workflow_dispatch:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Build the Docker image
        uses: actions/checkout@v3

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: longlivethepenguin/webmin
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - 
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
    
      - 
        uses: docker/login-action@v1
        name: Login to DockerHub
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      -
        name: Build and push Docker Webmin
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          extra_tags: 'latest'
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8
          cache-from: type=registry,ref=longlivethepenguin/webmin:latest
          cache-to: type=inline
#        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
